<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <title>Carousel Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <?php
        echo Phalcon\Tag::stylesheetLink(array("css/bootstrap.min.css"));
        echo Phalcon\Tag::stylesheetLink(array("https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", false));
        echo Phalcon\Tag::stylesheetLink(array("https://oss.maxcdn.com/respond/1.4.2/respond.min.js", false));
        echo Phalcon\Tag::stylesheetLink(array("css/carousel.css"));

    ?>

</head>
<!-- NAVBAR
================================================== -->
<body>
<div class="navbar-wrapper">
    <div class="container">

        <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Project name</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Home</a></li>
                        <li><a href="#about">About</a></li>
                        <li><a href="#contact">Contact</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li class="dropdown-header">Nav header</li>
                                <li><a href="#">Separated link</a></li>
                                <li><a href="#">One more separated link</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </div>
</div>


        <?php echo $this->getContent(); ?>

    <!-- FOOTER -->
    <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2014 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
    </footer>

</div><!-- /.container -->
<?php
    echo Phalcon\Tag::javascriptInclude(array('https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js', false));
    echo Phalcon\Tag::javascriptInclude(array('js/bootstrap.min.js'));
    echo Phalcon\Tag::javascriptInclude(array('js/docs.min.js'));
    echo Phalcon\Tag::javascriptInclude(array('js/ie10-viewport-bug-workaround.js'));

?>




</body>
</html>
